### ISSUE TITLE
Fails while parsing config

### ISSUE THREAD

**Issue by placydo** [brycied00d/fluent-plugin-splunk-http-eventcollector#11]
```
2017-05-03T08:42:39.981724108Z 2017-05-03 08:42:39 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2017-05-03T08:42:40.069330086Z /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config/basic_parser.rb:92:in `parse_error!': got incomplete JSON hash configuration at td-agent.conf line 410,9 (Fluent::ConfigParseError)
2017-05-03T08:42:40.069373824Z 409:    flush_interval 60s
2017-05-03T08:42:40.069382376Z 410: </match>
2017-05-03T08:42:40.069388881Z 
2017-05-03T08:42:40.069394422Z      ---------^
2017-05-03T08:42:40.069400047Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config/literal_parser.rb:244:in `scan_json'
2017-05-03T08:42:40.069406083Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config/literal_parser.rb:62:in `parse_literal'
2017-05-03T08:42:40.069411967Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config/v1_parser.rb:130:in `parse_element'
2017-05-03T08:42:40.069417661Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config/v1_parser.rb:95:in `parse_element'
2017-05-03T08:42:40.069423502Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config/v1_parser.rb:43:in `parse!'
2017-05-03T08:42:40.069429366Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config/v1_parser.rb:33:in `parse'
2017-05-03T08:42:40.069435844Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/config.rb:30:in `parse'
2017-05-03T08:42:40.069442053Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:480:in `read_config'
2017-05-03T08:42:40.069448419Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:144:in `start'
2017-05-03T08:42:40.069493109Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
2017-05-03T08:42:40.069502511Z 	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2017-05-03T08:42:40.069508779Z 	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2017-05-03T08:42:40.069515440Z 	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/bin/fluentd:5:in `<top (required)>'
2017-05-03T08:42:40.069521839Z 	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
2017-05-03T08:42:40.069527402Z 	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
2017-05-03T08:42:40.069533090Z 	from /usr/sbin/td-agent:7:in `load'
2017-05-03T08:42:40.069538401Z 	from /usr/sbin/td-agent:7:in `<main>'
```

Project Owner Edit: Wrapped log in code quoting for readability.

**Comment by brycied00d** [comment]
Could you please include a copy of the full `<match>` section (omit sensitive values, of course).

**Comment by brycied00d** [comment]
Hi @placydo, I'm closing this issue due to non-response. Please feel free to re-open when you can provide the requested information.

**Comment by WafflesVonMaple** [comment]
Having exact same Issue and log output. Here is my <match> sections

`# Do not directly collect fluentd's own logs to avoid infinite loops.
<match fluent.**>
  type null
</match>

<source>
  type tail
  path /var/log/containers/*.log
  pos_file /var/log/splunk-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag kubernetes.*
  format json
  read_from_head true
</source>

<filter kubernetes.**>
  type kubernetes_metadata
  verify_ssl "#{ENV['KUBE_VERIFY_SSL']}"
</filter>

<match **>
  type splunk-http-eventcollector
  server "#{ENV['SPLUNK_SERVER']}"
  verify false
  token "#{ENV['SPLUNK_AUTH']}"

  # Convert fluent tags to Splunk sources.
  # If you set an index, "check_index false" is required.
  index "#{ENV['SPLUNK_INDEX']}"
  check_index false
  source {TAG}
  sourcetype fluentd

  # TIMESTAMP: key1="value1" key2="value2" ...
  time_format none

  # Memory buffer with a short flush internal.
  buffer_type memory
  buffer_queue_limit 16
  buffer_chunk_limit 8m
  flush_interval 2s
</match>`

**Comment by brycied00d** [comment]
@WafflesVonMaple Taking a very quick look at this, it appears to be a fluentd configuration syntax/parser issue (and not directly related to this plugin). Googling for "fluentd parse_error got incomplete JSON hash configuration" comes up with lots of other individuals with the same sorts of issues.

From the [documentation](https://docs.fluentd.org/v0.12/articles/config-file#embedded-ruby-code), the example given is `env_param "foo-#{ENV["FOO_BAR"]}"` so I'd suggest using double-quotes for the Array reference, eg: `server "#{ENV["SPLUNK_SERVER"]}"`

**Comment by WafflesVonMaple** [comment]
Thanks for the quick response and help

**Comment by emalihin** [comment]
My attempts were failing with the same error, turns out that removing {TAG} made it work. Not sure what {TAG} refers to?

**Comment by jlsalmon** [comment]
@emalihin I think this was supposed to refer to the fluent tag and is either some kind of older placeholder format or a typo in the docs. I had success with using `${tag}` rather than `{TAG}`
